- RenderSharp.sln
> Added cppsrc to solution items for easy access in project view.

- Math/Types.cs
- Math/Vector.cs
- Math/Vector2.cs
- Math/Vector3.cs
- Math/Vector4.cs
- RendererCommon/Color/HSV.cs
- RendererCommon/Color/HSVA.cs
- RendererCommon/Color/RGB.cs
- RendererCommon/Color/RGBA.cs
- RendererCommon/Color/RGBAFloat.cs
- RendererCommon/Color/RGBFloat.cs
This PR adds more conversions for the Math vector types and introduces vector scalar division.
> Vector conversions and improvements

- RenderSharp/ExampleShaders.cs
- RendererCommon/Color/HSV.cs
- RendererCommon/Color/HSVA.cs
- RendererCommon/Color/RGB.cs
- RendererCommon/Color/RGBA.cs
- RendererCommon/Color/RGBAFloat.cs
- RendererCommon/Color/RGBFloat.cs
- RendererCommon/FragShader.cs
- RendererCommon/Texture.cs
This PR adds the shader delegate type for usage in rendering.
Closes #3
> Shader Port

- Math/Types.cs
- Math/Vector.cs
> Added vector rotation for FVec2

- RenderSharp/Program.cs
- RendererCommon/Frame.cs
> Frame port

- Math/Util.cs
- RenderSharp.sln
- RenderSharp/ExampleShaders.cs
- RenderSharp/Program.cs
- RenderSharp/RenderSharp.csproj
- Renderer2d/Renderer2d.cs
- Renderer2d/Renderer2d.csproj
- RendererCommon/Color/ColorFunctions.cs
- RendererCommon/FragShader.cs
- RendererCommon/Frame.cs
- RendererCommon/Texture.cs
- Scene/Scene2d.cs
- Scene/Scene2dInstance.cs
> Lil to justice/renderer port

- RenderSharp/Program.cs
- Renderer2d/Renderer2d.cs
- Scene/Scene2d.cs
- Scene/Scene2dInstance.cs
> Implemented actor ids

- RenderSharp/RenderSharp.csproj
- RenderSharp/Renderer/Renderer2d.cs
- RenderSharp/Renderer/Util.cs
- RenderSharp/RendererCommon/Color/RGB.cs
- RenderSharpExample/ExampleShaders.cs
- RenderSharpExample/Program.cs
> Fixed flipped coords issues

- RenderSharp/Renderer/Renderer2d.cs
- RenderSharp/Scene/Scene2d/Scene2d.cs
- RenderSharp/Scene/Scene2d/Scene2dInstance.cs
- RenderSharpExample/ExampleShaders.cs
- RenderSharpExample/Program.cs
> Cleaned up scene and actor

- RenderSharp/RenderSharp.csproj
> Updated RenderSharp.csproj for NuGet package generation

- RenderSharp/Renderer/Renderer2d.cs
- RenderSharp/Scene/Scene2d/Scene2d.cs
- RenderSharp/Scene/Scene2d/Scene2dInstance.cs
> Implemented planes for actors to allow user-controlled overdraw in 2d

- RenderSharp/Renderer/Renderer2d/Renderer.cs
- RenderSharp/Scene/Scene2d/Actor/Actor.cs
- RenderSharp/Scene/Scene2d/Actor/ActorIndex.cs
- RenderSharp/Scene/Scene2d/Actor/Line.cs
- RenderSharp/Scene/Scene2d/Builders/ActorBuilder.cs
- RenderSharp/Scene/Scene2d/Builders/LineBuilder.cs
- RenderSharp/Scene/Scene2d/Builders/SceneBuilder.cs
- RenderSharp/Scene/Scene2d/Scene/Camera.cs
- RenderSharp/Scene/Scene2d/Scene/Scene.cs
- RenderSharp/Scene/Scene2d/Scene/SceneInstance.cs
- RenderSharpExample/Program.cs
closes #97 
closes #81 
closes #79
> Implemented multi-camera support and cleaned up builder code

- RenderSharp/Common/Color/ColorFunctions.cs
- RenderSharp/Common/CoordShader.cs
- RenderSharp/Common/Texture.cs
- RenderSharp/Renderer/Renderer2d/Renderer.cs
- RenderSharp/Renderer/Util.cs
- RenderSharp/Scene/Scene2d/Actor/Actor.cs
- RenderSharp/Scene/Scene2d/Actor/Line.cs
- RenderSharp/Scene/Scene2d/Builders/ActorBuilder.cs
- RenderSharp/Scene/Scene2d/Builders/LineBuilder.cs
- RenderSharp/Scene/Scene2d/Builders/SceneBuilder.cs
- RenderSharp/Scene/Scene2d/Scene/Scene.cs
- RenderSharp/Scene/Scene2d/Scene/SceneInstance.cs
- RenderSharpExample/ExampleShaders.cs
- RenderSharpExample/Program.cs
and some bug fixes :P
closes #104 
closes #101
> Implemented Coordinate shaders and cleaned up rendering code

- RenderSharp/Common/Color/FRGB.cs
- RenderSharp/Common/Color/HSV.cs
- RenderSharp/Common/Color/RGB.cs
- RenderSharp/Render2d/Renderer2d/Transforms.cs
- RenderSharp/Render2d/Scene2d/Actor/Actor.cs
- RenderSharp/Render2d/Scene2d/Actor/Line.cs
- RenderSharp/Render2d/Scene2d/Builders/ActorBuilder.cs
- RenderSharp/Render3d/Renderer3d/Renderer.cs
- RenderSharp/Render3d/Renderer3d/Transforms.cs
- RenderSharp/Render3d/Renderer3d/Triangle.cs
- RenderSharp/Render3d/Scene3d/Actor/Actor.cs
- RenderSharp/Render3d/Scene3d/Actor/TriangleActor.cs
- RenderSharp/Render3d/Scene3d/Builders/ActorBuilder.cs
- RenderSharp/Render3d/Scene3d/Builders/SceneBuilder.cs
- RenderSharp/Render3d/Scene3d/Builders/TriangleActorBuilder.cs
- RenderSharp/Render3d/Scene3d/Scene/Camera.cs
- RenderSharp/Render3d/Scene3d/Scene/SceneInstance.cs
- RenderSharp/RenderSharp.csproj
- RenderSharpExample/Program.cs
> Triangle rendering in 3d

- RenderSharp/Render3d/Renderer3d/Primitives/Sphere.cs
- RenderSharp/Render3d/Renderer3d/Primitives/Triangle.cs
- RenderSharp/Render3d/Scene3d/Actor/Actor.cs
- RenderSharp/Render3d/Scene3d/Actor/SphereActor.cs
- RenderSharp/Render3d/Scene3d/Builders/SphereActorBuilder.cs
- RenderSharp/RenderSharp.csproj
- RenderSharpExample/Program.cs
> Sphere rendering

- RenderSharp/Render3d/Renderer3d/Primitives/Box.cs
- RenderSharp/Render3d/Renderer3d/Primitives/Sphere.cs
- RenderSharp/Render3d/Renderer3d/Primitives/Triangle.cs
- RenderSharp/Render3d/Renderer3d/Renderer.cs
- RenderSharp/Render3d/Renderer3d/RotorTransform.cs
- RenderSharp/Render3d/Renderer3d/Transforms.cs
- RenderSharp/Render3d/Scene3d/Actor/Actor.cs
- RenderSharp/Render3d/Scene3d/Actor/BoxActor.cs
- RenderSharp/Render3d/Scene3d/Actor/SphereActor.cs
- RenderSharp/Render3d/Scene3d/Builders/BoxActorBuilder.cs
- RenderSharp/Render3d/Scene3d/Builders/SphereActorBuilder.cs
- RenderSharpExample/Program.cs
> Box rendering and primitive rotation

- RenderSharp/Common/Color/FRGBA.cs
- RenderSharp/Render3d/Renderer3d/Primitives/Box.cs
- RenderSharp/Render3d/Renderer3d/Primitives/Sphere.cs
- RenderSharp/Render3d/Renderer3d/Renderer.cs
- RenderSharp/Render3d/Renderer3d/RotorTransform.cs
- RenderSharp/Render3d/Renderer3d/Transforms.cs
- RenderSharp/Render3d/Scene3d/Actor/Actor.cs
- RenderSharp/Render3d/Scene3d/Actor/BoxActor.cs
- RenderSharp/Render3d/Scene3d/Actor/SphereActor.cs
- RenderSharp/Render3d/Scene3d/Builders/SceneBuilder.cs
- RenderSharp/RenderSharp.csproj
- RenderSharpExample/Program.cs
Also fixes camera position issue
closes #134 
closes #122
> Depth buffering and depth map output

- RenderSharp/Render3d/Renderer3d/Renderer.cs
- RenderSharp/Render3d/Renderer3d/Transforms.cs
- RenderSharp/Render3d/Scene3d/Builders/SceneBuilder.cs
- RenderSharpExample/Program.cs
> Orthographic projection

- RenderSharp/Render3d/Renderer3d/Primitives/Cube.cs
- RenderSharpExample/Program.cs
Incredibly hackish but gets it done
closes #151
> Fix axis aligned cube

- RenderSharp/RenderSharp.csproj
> Bump version
